CREATE TABLE `ai_model` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `type` ENUM('LLM', 'EMBEDDING') NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `code` VARCHAR(191) NOT NULL,
  `provider` VARCHAR(191) NOT NULL,
  `protocol` VARCHAR(191) NOT NULL DEFAULT 'openai-compatible',
  `model` VARCHAR(191) NOT NULL,
  `base_url` VARCHAR(191) NOT NULL,
  `api_key` TEXT NOT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `is_default` BOOLEAN NOT NULL DEFAULT false,
  `sort` INTEGER NOT NULL DEFAULT 0,
  `max_context` INTEGER NULL,
  `max_response` INTEGER NULL,
  `quote_max_token` INTEGER NULL,
  `max_temperature` DOUBLE NULL,
  `default_system_prompt` TEXT NULL,
  `embedding_dimension` INTEGER NULL,
  `embedding_max_token` INTEGER NULL,
  `default_config` JSON NULL,
  `remark` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `ai_model_code_key`(`code`),
  INDEX `ai_model_type_is_active_sort_idx`(`type`, `is_active`, `sort`),
  INDEX `ai_model_type_is_default_idx`(`type`, `is_default`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
